# Site settings
title: Beautiful Rising
email: beautifulrising.org@gmail.com
description: "A Global Toolbox for Changemakers"
baseurl: ""
url: "http://beautifulrising.org"
# Site settings (custom)
image: "/img/br-logo-social.jpg"
domain: "beautifulrising.org"
twittername: "BeautRising"

# Build settings
markdown: kramdown
permalink: pretty
# Build settings (custom)
#mode: "development"
mode: "production"

# Prose configuration
prose:
  rooturl: '_posts'
  siteurl: 'http://beautifulrising.org/'
  relativeLinks: 'http://beautifulrising.org/links.jsonp'
  media: 'assets'
  ignore:
    - index.md
    - index.html
    - news.html
    - _config.yml
    - /_layouts
    - /_includes
    - /_plugins
    - /_data
    - /assets
    - /css
    - /img
    - /fonts
    - /js
    - .gitignore
    - .git
    - 404.html
    - google5844dd3c739be066.html
  metadata:
    _posts:
    - name: "date"
      field:
        element: "text"
        label: "Date (YYYY-MM-DD HH:MM:SS)"
    - name: "layout"
      field:
        element: "hidden"
        value: "post"
    - name: "title"
      field:
        element: "text"
        label: "title"
    - name: "author"
      field:
        element: "text"
        label: "author"
        value: "Søren Warburg"